### ISSUE TITLE
Support for samsung 

### ISSUE THREAD

**Issue by subhashay** [hashemi-hossein/memory-guardian#1]
Hi dev, found this app from HowtoMen video and I'm really interested in using it. 

But unfortunately on my samsung, the app is not working. I tried to get clear data which did not do anything. Even setting clearing interval did not help. 

Samsung clipboard retains data forever unless I manually clear it which makes this app really useful. Please let me know if its supported on samsung.

**Comment by hashemi-hossein** [comment]
Hi Subhashay,

Thank you for reaching out and telling me about this issue.
Could you try 1.1.1 version of the app and inform me about the problem being solved?

**Comment by hashemi-hossein** [comment]
Hi Subhashay,

Thank you for reaching out and telling me about this issue.
Could you try v1.1.1 and inform me about the problem being solved?

**Comment by subhashay** [comment]
Hi, thank you for the quick reply. 

Unfortunately it's not working. Samsung has a weird clipboard implimentation. It never clears clipboard. I just disabled Samsung keyboard and clipboard altogether and using SwiftKey which clears clipboard in 1 hr. Just a workaround that I'm ok with.

**Comment by hashemi-hossein** [comment]
I tested it on a Samsung Galaxy S6 devices and worked.
Could you tell me the model of your device?

**Comment by subhashay** [comment]
Using s23 ultra.

Discussion thread you might find useful: https://us.community.samsung.com/t5/Samsung-Apps-and-Services/Option-to-disable-clipboard-history/td-p/2589350
