### ISSUE TITLE
Might you move these buttons below?

### ISSUE THREAD

**Issue by serrq** [hashemi-hossein/memory-guardian#15]
![1000108066](https://github.com/hashemi-hossein/memory-guardian/assets/113377431/535b4ab1-2508-4112-b8e9-5dff333fe7fb)

**Comment by NikunjKhangwal** [comment]
+1
It would be easier to use

**Comment by hashemi-hossein** [comment]
@serrq @NikunjKhangwal What do you think about the new UI design?

**Comment by NikunjKhangwal** [comment]
@hashemi-hossein I love it. Very clean and simple.
