### ISSUE TITLE
Doesnt work on samsung one ui 6.1

### ISSUE THREAD

**Issue by nervigesic** [hashemi-hossein/memory-guardian#20]
The app doesnt work on samsung, it says it clears the clipboard in the app but when checking clipboard on samsung keyboard its all still there.

**Comment by hashemi-hossein** [comment]
It seems that Samsung devices use a different method for managing the clipboard so the clipboard can't be cleared in this way.
Currently there is no plan to fix this issue for Samsung devices.
Have a good time
