### ISSUE TITLE
Question/Request: app only gets most recent copied item from clipboard - get al items?

### ISSUE THREAD

**Issue by DB9-max** [hashemi-hossein/memory-guardian#21]
Not just recent clippy item but all clippy content?

**Comment by hashemi-hossein** [comment]
Hi @DB9-max 
It's not possible. Clipboard stores only one item at a time.

**Comment by hashemi-hossein** [comment]
keyboard apps usually have more permissions.
Anyway, the feature you suggested is not included in the goals of the app. However, I will think about it if more people request it.
Have a good time!
