### ISSUE TITLE
Reset countdown doesn't work at all

### ISSUE THREAD

**Issue by HarriBuh** [hashemi-hossein/memory-guardian#22]
Google Pixel 7
Android 14
App version 1.4.2

No matter what time I choose, the app will not delete/ reset the system's clipboard after the timer ran up.

I checked and verified with different numbers (60-200 seconds).

**Comment by hashemi-hossein** [comment]
Hi @HarriBuh,
Does the "Clear" button work?

**Comment by hashemi-hossein** [comment]
I checked it on a Google Pixel phone with Android version 14 but it works and I couldn't recreate the issue

Could you 1.disable "auto clear" option, 2.enable the notifications and 3.give it the notification permissions then 4.enable the "auto clear" option again so you should see a notification with a text in its body: "Memory Guardian is running in the background" 5. test auto clearing feature again and check notifications notifying about: "Clipboard cleared"
