### ISSUE TITLE
less than 15 minutes enhancement

### ISSUE THREAD

**Issue by Wjxfi** [hashemi-hossein/memory-guardian#3]

**Comment by EthicalGhost** [comment]
@hashemi-hossein Please consider this. Allowing custom time-set would be really nice. 1 minute as minimum would be appropriate.

**Comment by hashemi-hossein** [comment]
@Wjxfi @EthicalGhost @HarriBuh 
Hello all,

Thank you for your suggestion.
Please tell me your feedbacks on v1.3.0

Best,
Hossein Hashemi
