### ISSUE TITLE
Persistent notification in the drawer

### ISSUE THREAD

**Issue by serrq** [hashemi-hossein/memory-guardian#8]
I wish the "silent" notification never leave its place in notification drawer. Even if I try to remove it (when enabled).

**Comment by hashemi-hossein** [comment]
Hello Serrq,

It's a non-dismissable notification on Android versions below 14 but the behaviour has been changed in Android 14:
https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications

You can use the quick setting tile I added in v1.3.3 to pause
